### ISSUE TITLE
Can't save to Readeck because CORS error

### ISSUE THREAD

**Issue by iloeng** [RSSNext/Folo#3779]
### Platform

Desktop - Web

### Describe the bug

Using a self-hosted Readeck, and have added the following header into nginx config:

```
location /api/bookmarks {

        add_header 'Access-Control-Allow-Origin' 'https://app.follow.is';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With';
        add_header 'Access-Control-Allow-Credentials' 'true';

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }
```

still can't save to Readeck

### Environment

Windows 11 + Chrome 136.0.7103.114 

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [x] This issue is valid

### Contributions

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by shadowfish07** [comment]
I've found the root of the problem! It seems the core issue is that the ⁠OPTIONS request used for CORS is also being checked for authentication. However, by default, browsers do not send cookies with an ⁠OPTIONS request, which inevitably causes it to return a 401 Unauthorized error. I'm not sure if this is a bug in the application, but I managed to bypass this restriction using Caddy.

```
:80 {
    # Define a matcher for requests using the OPTIONS method.
    @options method OPTIONS

    # For OPTIONS requests, respond immediately with 200 OK and no body.
    # The CORS headers defined below will be added to this response.
    respond @options 200

    # I use cloudflare tunnel, so I need to add the following statement
    # For all other requests, reverse proxy to the backend application.
    reverse_proxy app:8000 {
        # Core configuration: Tells Caddy it's behind a trusted reverse proxy.
        # This allows Caddy to correctly use headers like X-Forwarded-For.
        trusted_proxies private_ranges
    }

    # Add response headers to allow CORS requests from any website.
    # These headers are applied to ALL responses, including the preflight OPTIONS response.
    header {
        Access-Control-Allow-Origin *
        Access-Control-Allow-Methods *
        Access-Control-Allow-Headers *
    }
}
```

Note:

For convenience, I have allowed access from all domains. If the ⁠Access-Control-Allow-* headers are not added, folo will report a failure when calling the Readeck API, but the article has actually been saved successfully.

And my docker compose file:

```
services:
  app:
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck

    environment:
      - READECK_LOG_LEVEL=info
      - READECK_SERVER_HOST=0.0.0.0
      - READECK_SERVER_PORT=8000
    volumes:
      - ./readeck-data:/readeck
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    ports:
      - "8000:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    restart: unless-stopped
    depends_on:
      - app

volumes:
  caddy_data:
```

I also submitted an issue in [Readeck's repository](https://codeberg.org/readeck/readeck/issues/689)
